// Novidades de cada versão, em todos os idiomas, mostradas uma vez depois de
// atualizar o Polvo. O CHANGELOG.md (notas da release) segue o texto em pt.
import type { Locale } from "./i18n";

export interface ReleaseNotes {
  version: string;
  notes: Record<Locale, string[]>;
}

export const RELEASES: ReleaseNotes[] = [
  {
    version: "0.3.7",
    notes: {
      pt: [
        "**Ctrl + clique abre qualquer arquivo do terminal**: Markdown no visualizador do Polvo, imagens numa prévia em tela cheia e o resto no programa padrão do Windows. Para mostrar o arquivo ou a pasta no Explorer, use **Ctrl + Shift + clique**. Executáveis e scripts nunca rodam: só aparecem selecionados no Explorer.",
        "**Prévia de imagens**: zoom com a roda, arrastar para mover, + − 0 e 1 para 100%. Abra no programa padrão, mostre no Explorer, copie a imagem (Ctrl+C) ou o caminho.",
        "**Caminhos quebrados em várias linhas**: quando o Claude Code ou outro CLI corta um caminho longo no fim da linha, o Ctrl + clique em qualquer pedaço abre o arquivo inteiro.",
        "**Ctrl + V cola arquivos no chat**: arquivos copiados no Explorer vão para `.polvo/pasted` do projeto (fora do Git) e entram como `@caminho`; os que já estão no projeto só são referenciados. Um print no Claude Code vira o Alt + V dele; nos outros CLIs é salvo como PNG e referenciado.",
        "**Novos atalhos na Ajuda**: Ctrl + clique, Ctrl + Shift + clique e Ctrl + V.",
      ],
      en: [
        "**Ctrl + click opens any file from the terminal**: Markdown in Polvo's viewer, images in a full-screen preview and everything else in the Windows default app. To show the file or folder in Explorer, use **Ctrl + Shift + click**. Executables and scripts never run: they're only selected in Explorer.",
        "**Image preview**: wheel to zoom, drag to pan, + − 0 and 1 for 100%. Open in the default app, show in Explorer, copy the image (Ctrl+C) or its path.",
        "**Paths broken across lines**: when Claude Code or another CLI cuts a long path at the end of a line, Ctrl + click on any piece opens the whole file.",
        "**Ctrl + V pastes files into the chat**: files copied in Explorer go to the project's `.polvo/pasted` (ignored by Git) and come in as `@path`; files already in the project are just referenced. A screenshot in Claude Code becomes its Alt + V; in other CLIs it's saved as PNG and referenced.",
        "**New shortcuts in Help**: Ctrl + click, Ctrl + Shift + click and Ctrl + V.",
      ],
      es: [
        "**Ctrl + clic abre cualquier archivo del terminal**: Markdown en el visor de Polvo, imágenes en una vista previa a pantalla completa y el resto en la aplicación predeterminada de Windows. Para mostrar el archivo o la carpeta en el Explorador, usa **Ctrl + Mayús + clic**. Los ejecutables y scripts nunca se ejecutan: solo se seleccionan en el Explorador.",
        "**Vista previa de imágenes**: rueda para zoom, arrastrar para mover, + − 0 y 1 para 100%. Abre en la app predeterminada, muestra en el Explorador, copia la imagen (Ctrl+C) o la ruta.",
        "**Rutas partidas en varias líneas**: cuando Claude Code u otro CLI corta una ruta larga al final de la línea, Ctrl + clic en cualquier parte abre el archivo completo.",
        "**Ctrl + V pega archivos en el chat**: los archivos copiados en el Explorador van a `.polvo/pasted` del proyecto (fuera de Git) y entran como `@ruta`; los que ya están en el proyecto solo se referencian. Una captura en Claude Code se convierte en su Alt + V; en los otros CLIs se guarda como PNG y se referencia.",
        "**Nuevos atajos en la Ayuda**: Ctrl + clic, Ctrl + Mayús + clic y Ctrl + V.",
      ],
      fr: [
        "**Ctrl + clic ouvre n'importe quel fichier du terminal** : le Markdown dans la visionneuse de Polvo, les images dans un aperçu plein écran et le reste dans l'application par défaut de Windows. Pour afficher le fichier ou le dossier dans l'Explorateur, utilisez **Ctrl + Maj + clic**. Les exécutables et scripts ne sont jamais lancés : ils sont seulement sélectionnés dans l'Explorateur.",
        "**Aperçu des images** : molette pour zoomer, glisser pour déplacer, + − 0 et 1 pour 100 %. Ouvrez dans l'application par défaut, affichez dans l'Explorateur, copiez l'image (Ctrl+C) ou son chemin.",
        "**Chemins coupés sur plusieurs lignes** : quand Claude Code ou un autre CLI coupe un long chemin en fin de ligne, Ctrl + clic sur n'importe quel morceau ouvre le fichier entier.",
        "**Ctrl + V colle des fichiers dans le chat** : les fichiers copiés dans l'Explorateur vont dans `.polvo/pasted` du projet (hors de Git) et arrivent sous la forme `@chemin` ; ceux déjà dans le projet sont simplement référencés. Une capture dans Claude Code devient son Alt + V ; dans les autres CLI, elle est enregistrée en PNG et référencée.",
        "**Nouveaux raccourcis dans l'Aide** : Ctrl + clic, Ctrl + Maj + clic et Ctrl + V.",
      ],
      de: [
        "**Strg + Klick öffnet jede Datei aus dem Terminal**: Markdown im Polvo-Viewer, Bilder in einer Vollbildvorschau und alles andere in der Windows-Standard-App. Um Datei oder Ordner im Explorer anzuzeigen, nutze **Strg + Umschalt + Klick**. Ausführbare Dateien und Skripte werden nie gestartet, nur im Explorer markiert.",
        "**Bildvorschau**: Mausrad zum Zoomen, Ziehen zum Verschieben, + − 0 und 1 für 100 %. In der Standard-App öffnen, im Explorer anzeigen, Bild (Strg+C) oder Pfad kopieren.",
        "**Über mehrere Zeilen umgebrochene Pfade**: Wenn Claude Code oder ein anderes CLI einen langen Pfad am Zeilenende umbricht, öffnet Strg + Klick auf ein beliebiges Stück die ganze Datei.",
        "**Strg + V fügt Dateien in den Chat ein**: Im Explorer kopierte Dateien landen in `.polvo/pasted` des Projekts (von Git ignoriert) und kommen als `@pfad` an; Dateien, die schon im Projekt liegen, werden nur referenziert. Ein Screenshot wird in Claude Code zu dessen Alt + V; in anderen CLIs wird er als PNG gespeichert und referenziert.",
        "**Neue Tastenkürzel in der Hilfe**: Strg + Klick, Strg + Umschalt + Klick und Strg + V.",
      ],
      it: [
        "**Ctrl + clic apre qualsiasi file dal terminale**: il Markdown nel visualizzatore di Polvo, le immagini in un'anteprima a schermo intero e il resto nell'app predefinita di Windows. Per mostrare il file o la cartella in Esplora file, usa **Ctrl + Maiusc + clic**. Eseguibili e script non vengono mai eseguiti: vengono solo selezionati in Esplora file.",
        "**Anteprima delle immagini**: rotellina per lo zoom, trascina per spostare, + − 0 e 1 per il 100%. Apri nell'app predefinita, mostra in Esplora file, copia l'immagine (Ctrl+C) o il percorso.",
        "**Percorsi spezzati su più righe**: quando Claude Code o un altro CLI taglia un percorso lungo a fine riga, Ctrl + clic su qualsiasi pezzo apre il file intero.",
        "**Ctrl + V incolla file nella chat**: i file copiati in Esplora file finiscono in `.polvo/pasted` del progetto (escluso da Git) ed entrano come `@percorso`; quelli già nel progetto vengono solo citati. Uno screenshot in Claude Code diventa il suo Alt + V; negli altri CLI viene salvato come PNG e citato.",
        "**Nuove scorciatoie nella Guida**: Ctrl + clic, Ctrl + Maiusc + clic e Ctrl + V.",
      ],
      ja: [
        "**Ctrl + クリックでターミナル内のファイルを開く**：Markdown は Polvo のビューアー、画像は全画面プレビュー、それ以外は Windows の既定のアプリで開きます。エクスプローラーで表示するには **Ctrl + Shift + クリック**。実行ファイルやスクリプトは実行されず、エクスプローラーで選択されるだけです。",
        "**画像プレビュー**：ホイールでズーム、ドラッグで移動、+ − 0、1 で 100%。既定のアプリで開く、エクスプローラーで表示、画像 (Ctrl+C) やパスのコピーができます。",
        "**複数行に分かれたパス**：Claude Code などの CLI が長いパスを行末で折り返しても、どの部分を Ctrl + クリックしてもファイル全体が開きます。",
        "**Ctrl + V でファイルをチャットに貼り付け**：エクスプローラーでコピーしたファイルはプロジェクトの `.polvo/pasted`（Git の対象外）に置かれ、`@パス` として入力されます。プロジェクト内のファイルは参照だけです。スクリーンショットは Claude Code では Alt + V として渡され、他の CLI では PNG として保存・参照されます。",
        "**ヘルプに新しいショートカット**：Ctrl + クリック、Ctrl + Shift + クリック、Ctrl + V。",
      ],
      zh: [
        "**Ctrl + 点击打开终端中的任意文件**：Markdown 在 Polvo 查看器中打开，图片以全屏预览显示，其他文件用 Windows 默认应用打开。要在资源管理器中显示文件或文件夹，请使用 **Ctrl + Shift + 点击**。可执行文件和脚本永远不会运行，只会在资源管理器中被选中。",
        "**图片预览**：滚轮缩放、拖动平移，+ − 0 以及 1 恢复 100%。可用默认应用打开、在资源管理器中显示、复制图片 (Ctrl+C) 或路径。",
        "**跨行断开的路径**：Claude Code 等 CLI 在行尾截断长路径时，按住 Ctrl 点击任意部分都会打开完整文件。",
        "**Ctrl + V 将文件粘贴到聊天**：在资源管理器中复制的文件会放入项目的 `.polvo/pasted`（不纳入 Git），并以 `@路径` 输入；已在项目中的文件只做引用。截图在 Claude Code 中会转为它的 Alt + V；在其他 CLI 中保存为 PNG 并引用。",
        "**帮助中新增快捷键**：Ctrl + 点击、Ctrl + Shift + 点击和 Ctrl + V。",
      ],
      ko: [
        "**Ctrl + 클릭으로 터미널의 파일 열기**: Markdown은 Polvo 뷰어에서, 이미지는 전체 화면 미리 보기로, 나머지는 Windows 기본 앱으로 엽니다. 탐색기에서 파일이나 폴더를 표시하려면 **Ctrl + Shift + 클릭**을 사용하세요. 실행 파일과 스크립트는 실행되지 않고 탐색기에서 선택만 됩니다.",
        "**이미지 미리 보기**: 휠로 확대/축소, 드래그로 이동, + − 0, 1은 100%. 기본 앱으로 열기, 탐색기에서 표시, 이미지(Ctrl+C)나 경로 복사가 가능합니다.",
        "**여러 줄로 나뉜 경로**: Claude Code 등 CLI가 긴 경로를 줄 끝에서 자르더라도 아무 부분이나 Ctrl + 클릭하면 전체 파일이 열립니다.",
        "**Ctrl + V로 파일을 채팅에 붙여넣기**: 탐색기에서 복사한 파일은 프로젝트의 `.polvo/pasted`(Git 제외)로 복사되어 `@경로`로 입력됩니다. 이미 프로젝트에 있는 파일은 참조만 합니다. 스크린샷은 Claude Code에서는 Alt + V로 전달되고, 다른 CLI에서는 PNG로 저장되어 참조됩니다.",
        "**도움말에 새 단축키**: Ctrl + 클릭, Ctrl + Shift + 클릭, Ctrl + V.",
      ],
      ru: [
        "**Ctrl + клик открывает любой файл из терминала**: Markdown — во встроенном просмотрщике Polvo, изображения — в полноэкранном просмотре, остальное — в приложении Windows по умолчанию. Чтобы показать файл или папку в Проводнике, используйте **Ctrl + Shift + клик**. Исполняемые файлы и скрипты никогда не запускаются, а только выделяются в Проводнике.",
        "**Просмотр изображений**: колесо для масштаба, перетаскивание для перемещения, + − 0 и 1 для 100 %. Откройте в приложении по умолчанию, покажите в Проводнике, скопируйте изображение (Ctrl+C) или путь.",
        "**Пути, разбитые на несколько строк**: если Claude Code или другой CLI обрезал длинный путь в конце строки, Ctrl + клик по любой части откроет весь файл.",
        "**Ctrl + V вставляет файлы в чат**: файлы, скопированные в Проводнике, попадают в `.polvo/pasted` проекта (вне Git) и вставляются как `@путь`; файлы, уже лежащие в проекте, просто упоминаются. Скриншот в Claude Code превращается в его Alt + V; в других CLI сохраняется как PNG и упоминается.",
        "**Новые сочетания клавиш в Справке**: Ctrl + клик, Ctrl + Shift + клик и Ctrl + V.",
      ],
    },
  },
  {
    version: "0.3.6",
    notes: {
      pt: [
        "**Ordem dos projetos fixa**: a barra lateral não reordena mais os projetos conforme as sessões abrem e fecham. Arraste um projeto (ou o ícone, com a barra recolhida) para mudar a posição; todas as janelas seguem a mesma ordem.",
        "**Encerrar pela barra lateral**: passe o mouse numa sessão e clique no X; um segundo clique em “Encerrar?” confirma.",
        "**Ctrl + clique em caminhos no terminal**, como no VS Code: pastas abrem no Explorer, arquivos aparecem selecionados no Explorer e arquivos Markdown abrem no visualizador do Polvo.",
        "**Correções no Git**: o cartão “Puxar” da tela sem alterações não sai mais deformado, os avatares do Histórico ficam alinhados e os cartões de Meu trabalho não piscam mais.",
      ],
      en: [
        "**Fixed project order**: the sidebar no longer reorders projects as sessions open and close. Drag a project (or its icon, with the sidebar collapsed) to move it; every window follows the same order.",
        "**End sessions from the sidebar**: hover a session and click the X; a second click on “End?” confirms.",
        "**Ctrl + click paths in the terminal**, like in VS Code: folders open in Explorer, files show up selected in Explorer and Markdown files open in Polvo's viewer.",
        "**Git fixes**: the “Pull” card on the no-changes screen is no longer misshapen, History avatars are aligned and the My work cards no longer flicker.",
      ],
      es: [
        "**Orden de proyectos fijo**: la barra lateral ya no reordena los proyectos al abrir y cerrar sesiones. Arrastra un proyecto (o su icono, con la barra contraída) para moverlo; todas las ventanas siguen el mismo orden.",
        "**Cierra sesiones desde la barra lateral**: pasa el ratón sobre una sesión y haz clic en la X; un segundo clic en “¿Cerrar?” confirma.",
        "**Ctrl + clic en rutas del terminal**, como en VS Code: las carpetas se abren en el Explorador, los archivos aparecen seleccionados en el Explorador y los Markdown se abren en el visor de Polvo.",
        "**Correcciones en Git**: la tarjeta “Pull” de la pantalla sin cambios ya no sale deformada, los avatares del Historial quedan alineados y las tarjetas de Mi trabajo ya no parpadean.",
      ],
      fr: [
        "**Ordre des projets fixe** : la barre latérale ne réordonne plus les projets à l'ouverture et à la fermeture des sessions. Glissez un projet (ou son icône, barre repliée) pour le déplacer ; toutes les fenêtres suivent le même ordre.",
        "**Fermez une session depuis la barre latérale** : survolez une session et cliquez sur le X ; un second clic sur « Fermer ? » confirme.",
        "**Ctrl + clic sur les chemins du terminal**, comme dans VS Code : les dossiers s'ouvrent dans l'Explorateur, les fichiers y apparaissent sélectionnés et les fichiers Markdown s'ouvrent dans la visionneuse de Polvo.",
        "**Corrections Git** : la carte « Pull » de l'écran sans modifications n'est plus déformée, les avatars de l'Historique sont alignés et les cartes de Mon travail ne clignotent plus.",
      ],
      de: [
        "**Feste Projektreihenfolge**: Die Seitenleiste sortiert Projekte nicht mehr um, wenn Sitzungen geöffnet und geschlossen werden. Ziehen Sie ein Projekt (oder sein Symbol bei eingeklappter Leiste), um es zu verschieben; alle Fenster folgen derselben Reihenfolge.",
        "**Sitzungen in der Seitenleiste beenden**: Mit der Maus über eine Sitzung fahren und auf das X klicken; ein zweiter Klick auf „Beenden?“ bestätigt.",
        "**Strg + Klick auf Pfade im Terminal**, wie in VS Code: Ordner öffnen sich im Explorer, Dateien werden im Explorer markiert und Markdown-Dateien öffnen sich im Viewer von Polvo.",
        "**Git-Korrekturen**: Die Karte „Pull“ im Bildschirm ohne Änderungen ist nicht mehr verzerrt, die Avatare im Verlauf sind ausgerichtet und die Karten in Meine Arbeit flackern nicht mehr.",
      ],
      it: [
        "**Ordine dei progetti fisso**: la barra laterale non riordina più i progetti quando le sessioni si aprono e si chiudono. Trascina un progetto (o la sua icona, con la barra compressa) per spostarlo; tutte le finestre seguono lo stesso ordine.",
        "**Chiudi le sessioni dalla barra laterale**: passa il mouse su una sessione e fai clic sulla X; un secondo clic su “Chiudere?” conferma.",
        "**Ctrl + clic sui percorsi nel terminale**, come in VS Code: le cartelle si aprono in Esplora file, i file vi appaiono selezionati e i file Markdown si aprono nel visualizzatore di Polvo.",
        "**Correzioni Git**: la scheda “Pull” della schermata senza modifiche non è più deformata, gli avatar della Cronologia sono allineati e le schede di Il mio lavoro non sfarfallano più.",
      ],
      ja: [
        "**プロジェクトの並び順を固定**：セッションの開閉でサイドバーのプロジェクトが並び替わらなくなりました。プロジェクト（サイドバーを折りたたんでいるときはアイコン）をドラッグすると位置を変えられ、すべてのウィンドウで同じ順序になります。",
        "**サイドバーからセッションを終了**：セッションにマウスを合わせて X をクリックし、「終了?」をもう一度クリックして確定します。",
        "**ターミナルのパスを Ctrl + クリック**（VS Code と同様）：フォルダーはエクスプローラーで開き、ファイルはエクスプローラーで選択された状態で表示され、Markdown ファイルは Polvo のビューアーで開きます。",
        "**Git の修正**：変更なし画面の「プル」カードが崩れなくなり、履歴のアバターが揃い、マイワークのカードがちらつかなくなりました。",
      ],
      zh: [
        "**项目顺序固定**：侧边栏不再随着会话的打开和关闭而重新排列项目。拖动项目（侧边栏折叠时拖动图标）即可调整位置，所有窗口都使用相同的顺序。",
        "**在侧边栏结束会话**：将鼠标悬停在会话上并点击 X，再次点击“结束?”确认。",
        "**在终端中 Ctrl + 点击路径**，与 VS Code 相同：文件夹在资源管理器中打开，文件在资源管理器中被选中显示，Markdown 文件在 Polvo 的查看器中打开。",
        "**Git 修复**：无更改界面的“拉取”卡片不再变形，历史中的头像已对齐，“我的工作”中的卡片不再闪烁。",
      ],
      ko: [
        "**프로젝트 순서 고정**: 세션을 열고 닫아도 사이드바의 프로젝트 순서가 바뀌지 않습니다. 프로젝트(사이드바를 접었을 때는 아이콘)를 끌어 위치를 바꿀 수 있으며, 모든 창이 같은 순서를 따릅니다.",
        "**사이드바에서 세션 종료**: 세션에 마우스를 올리고 X를 클릭한 뒤 “종료?”를 한 번 더 클릭해 확인합니다.",
        "**터미널의 경로를 Ctrl + 클릭** (VS Code처럼): 폴더는 탐색기에서 열리고, 파일은 탐색기에서 선택된 상태로 표시되며, Markdown 파일은 Polvo 뷰어에서 열립니다.",
        "**Git 수정**: 변경 사항 없음 화면의 “풀” 카드가 더 이상 찌그러지지 않고, 기록의 아바타가 정렬되며, 내 작업의 카드가 더 이상 깜박이지 않습니다.",
      ],
      ru: [
        "**Порядок проектов закреплён**: боковая панель больше не переставляет проекты при открытии и закрытии сеансов. Перетащите проект (или его значок, если панель свёрнута), чтобы переместить его; все окна используют один и тот же порядок.",
        "**Завершение сеансов из боковой панели**: наведите указатель на сеанс и нажмите X; второй щелчок по «Завершить?» подтверждает.",
        "**Ctrl + щелчок по путям в терминале**, как в VS Code: папки открываются в Проводнике, файлы показываются в нём выделенными, а файлы Markdown открываются в просмотрщике Polvo.",
        "**Исправления Git**: карточка «Pull» на экране без изменений больше не искажается, аватары в Истории выровнены, а карточки в «Моей работе» больше не мигают.",
      ],
    },
  },
  {
    version: "0.3.5",
    notes: {
      pt: [
        "**Marque arquivos nas Alterações**: marcar e desmarcar é instantâneo e não mexe no stage. Shift ou Ctrl+clique marca vários; com o botão direito sobre um marcado, descarte, guarde num stash ou coloque no stage todos de uma vez. O commit leva só os marcados.",
        "**Resumo automático**: com um arquivo só no commit, o resumo vem pronto (“Cria”, “Atualiza”, “Exclui” ou “Renomeia” + o nome do arquivo), no idioma do Polvo.",
        "**Divisória em todas as abas do Git**: Histórico, Branches e PRs também têm a divisória entre a lista e o conteúdo, cada uma com a largura lembrada.",
        "**Autores no Histórico**: cada commit mostra a foto do autor (GitHub ou Gravatar) ou as iniciais do nome.",
      ],
      en: [
        "**Check files in Changes**: checking and unchecking is instant and doesn't touch the stage. Shift or Ctrl+click checks several; right-click a checked file to discard, stash or stage them all at once. The commit takes only the checked files.",
        "**Automatic summary**: with a single file in the commit, the summary is ready (“Create”, “Update”, “Delete” or “Rename” + the file name), in Polvo's language.",
        "**Divider in every Git tab**: History, Branches and PRs also have the divider between the list and the content, each remembering its width.",
        "**Authors in History**: each commit shows the author's photo (GitHub or Gravatar) or their initials.",
      ],
      es: [
        "**Marca archivos en Cambios**: marcar y desmarcar es instantáneo y no toca el stage. Mayús o Ctrl+clic marca varios; con clic derecho sobre uno marcado, descarta, guarda en un stash o pasa al stage todos a la vez. El commit lleva solo los marcados.",
        "**Resumen automático**: con un solo archivo en el commit, el resumen viene listo (“Crea”, “Actualiza”, “Elimina” o “Renombra” + el nombre del archivo), en el idioma de Polvo.",
        "**Separador en todas las pestañas de Git**: Historial, Ramas y PRs también tienen el separador entre la lista y el contenido, cada una recordando su ancho.",
        "**Autores en el Historial**: cada commit muestra la foto del autor (GitHub o Gravatar) o sus iniciales.",
      ],
      fr: [
        "**Cochez des fichiers dans Modifications** : cocher et décocher est instantané et ne touche pas à l'index. Maj ou Ctrl+clic en coche plusieurs ; clic droit sur un fichier coché pour tout annuler, remiser ou indexer d'un coup. Le commit ne prend que les fichiers cochés.",
        "**Résumé automatique** : avec un seul fichier dans le commit, le résumé est prêt (« Crée », « Met à jour », « Supprime » ou « Renomme » + le nom du fichier), dans la langue de Polvo.",
        "**Séparateur dans tous les onglets Git** : Historique, Branches et PR ont aussi le séparateur entre la liste et le contenu, chacun mémorisant sa largeur.",
        "**Auteurs dans l'Historique** : chaque commit affiche la photo de l'auteur (GitHub ou Gravatar) ou ses initiales.",
      ],
      de: [
        "**Dateien in Änderungen markieren**: Markieren und Abwählen geht sofort und ändert den Index nicht. Umschalt- oder Strg+Klick markiert mehrere; per Rechtsklick auf eine markierte Datei alle auf einmal verwerfen, stashen oder stagen. Der Commit nimmt nur die markierten Dateien.",
        "**Automatische Zusammenfassung**: Bei nur einer Datei im Commit steht die Zusammenfassung schon da („erstellen“, „aktualisieren“, „löschen“ oder „umbenennen“ + Dateiname), in der Sprache von Polvo.",
        "**Trennlinie in allen Git-Tabs**: Verlauf, Branches und PRs haben ebenfalls die Trennlinie zwischen Liste und Inhalt, jeweils mit gemerkter Breite.",
        "**Autoren im Verlauf**: Jeder Commit zeigt das Foto des Autors (GitHub oder Gravatar) oder seine Initialen.",
      ],
      it: [
        "**Seleziona file in Modifiche**: selezionare e deselezionare è istantaneo e non tocca lo stage. Maiusc o Ctrl+clic ne seleziona diversi; con il tasto destro su uno selezionato puoi scartarli, metterli nello stash o nello stage tutti insieme. Il commit prende solo i selezionati.",
        "**Riepilogo automatico**: con un solo file nel commit, il riepilogo è già pronto (“Crea”, “Aggiorna”, “Elimina” o “Rinomina” + il nome del file), nella lingua di Polvo.",
        "**Divisore in tutte le schede Git**: Cronologia, Branch e PR hanno anch'esse il divisore tra elenco e contenuto, ognuna con la larghezza ricordata.",
        "**Autori nella Cronologia**: ogni commit mostra la foto dell'autore (GitHub o Gravatar) o le sue iniziali.",
      ],
      ja: [
        "**変更画面でファイルをチェック**：チェックの切り替えは即座に反映され、ステージには影響しません。Shift または Ctrl+クリックで複数をチェックし、チェック済みのファイルを右クリックすると、まとめて破棄・スタッシュ・ステージできます。コミットにはチェックしたファイルだけが含まれます。",
        "**自動サマリー**：コミットするファイルが 1 つだけのとき、サマリーが自動で入ります（「作成」「更新」「削除」「名前変更」+ ファイル名、Polvo の表示言語で）。",
        "**すべての Git タブに仕切り**：履歴、ブランチ、PR にも一覧と内容の間の仕切りが付き、それぞれ幅が保存されます。",
        "**履歴に作成者を表示**：各コミットに作成者の写真（GitHub または Gravatar）、またはイニシャルが表示されます。",
      ],
      zh: [
        "**在更改中勾选文件**：勾选和取消勾选即时生效，不影响暂存区。Shift 或 Ctrl+点击可勾选多个；右键点击已勾选的文件，可一次性丢弃、贮藏或暂存它们。提交只包含已勾选的文件。",
        "**自动摘要**：提交只有一个文件时，摘要会自动填好（“创建”“更新”“删除”或“重命名” + 文件名），使用 Polvo 的界面语言。",
        "**所有 Git 标签页都有分隔线**：历史、分支和 PR 也有列表与内容之间的分隔线，并各自记住宽度。",
        "**历史中显示作者**：每个提交显示作者的照片（GitHub 或 Gravatar）或姓名首字母。",
      ],
      ko: [
        "**변경 사항에서 파일 선택**: 선택과 해제가 즉시 반영되며 스테이지는 건드리지 않습니다. Shift 또는 Ctrl+클릭으로 여러 개를 선택하고, 선택한 파일을 오른쪽 클릭해 한 번에 버리기, 스태시, 스테이지할 수 있습니다. 커밋에는 선택한 파일만 들어갑니다.",
        "**자동 요약**: 커밋에 파일이 하나뿐이면 요약이 자동으로 채워집니다(“생성”, “업데이트”, “삭제”, “이름 변경” + 파일 이름, Polvo 언어로).",
        "**모든 Git 탭에 구분선**: 기록, 브랜치, PR에도 목록과 내용 사이의 구분선이 생기고 각각 너비를 기억합니다.",
        "**기록에 작성자 표시**: 각 커밋에 작성자 사진(GitHub 또는 Gravatar)이나 이름 이니셜이 표시됩니다.",
      ],
      ru: [
        "**Отмечайте файлы в Изменениях**: отметка мгновенная и не трогает индекс. Shift или Ctrl+клик отмечает несколько; правый клик по отмеченному файлу позволяет сразу отменить, спрятать в stash или добавить в индекс их все. Коммит берёт только отмеченные файлы.",
        "**Автоматическое описание**: если в коммите один файл, описание уже готово («Создать», «Обновить», «Удалить» или «Переименовать» + имя файла) на языке Polvo.",
        "**Разделитель во всех вкладках Git**: в Истории, Ветках и PR тоже есть разделитель между списком и содержимым, и каждая вкладка запоминает ширину.",
        "**Авторы в Истории**: у каждого коммита видно фото автора (GitHub или Gravatar) или его инициалы.",
      ],
    },
  },
  {
    version: "0.3.4",
    notes: {
      pt: [
        "**Visual plano e temas claro e escuro**: siga o Windows ou escolha o tema em Ajustes. Terminais, editor e diagramas acompanham o tema; você também pode manter o terminal escuro.",
        "**Painel Git mais confortável**: arraste a divisória entre a lista de arquivos e o diff em Alterações. O botão Buscar mantém sua posição durante a busca.",
        "**Confirmação ao encerrar e remover**: o X da gaveta do Quadro pede um segundo clique para encerrar a sessão. Clique novamente no cartão para fechar apenas a gaveta. Tirar um projeto da barra também pede confirmação.",
        "**Nova janela pelo menu do monitor**: abra outra janela no menu “Levar esta janela para outro monitor”, como mostra a dica do onboarding.",
      ],
      en: [
        "**Flat design and light and dark themes**: follow Windows or choose a theme in Settings. Terminals, the editor and diagrams follow the theme; you can also keep terminals dark.",
        "**A more comfortable Git panel**: drag the divider between the file list and diff in Changes. The Fetch button stays in place while fetching.",
        "**Confirm before closing and removing**: the Board drawer's X requires a second click to end the session. Click the selected card again to close only the drawer. Removing a project from the sidebar also requires confirmation.",
        "**New window from the monitor menu**: open another window from “Move this window to another monitor”, as shown in the onboarding hint.",
      ],
      es: [
        "**Diseño plano y temas claro y oscuro**: sigue Windows o elige el tema en Ajustes. Las terminales, el editor y los diagramas siguen el tema; también puedes mantener la terminal oscura.",
        "**Panel Git más cómodo**: arrastra el separador entre la lista de archivos y el diff en Cambios. El botón Buscar mantiene su posición durante la búsqueda.",
        "**Confirmación al cerrar y quitar**: la X del panel del Tablero requiere un segundo clic para terminar la sesión. Haz clic de nuevo en la tarjeta seleccionada para cerrar solo el panel. Quitar un proyecto de la barra lateral también requiere confirmación.",
        "**Nueva ventana desde el menú del monitor**: abre otra ventana desde el menú para mover esta ventana a otro monitor, como muestra la ayuda inicial.",
      ],
      fr: [
        "**Design plat et thèmes clair et sombre** : suivez Windows ou choisissez le thème dans les Réglages. Les terminaux, l'éditeur et les diagrammes suivent le thème ; vous pouvez aussi garder les terminaux sombres.",
        "**Panneau Git plus confortable** : faites glisser le séparateur entre la liste des fichiers et le diff dans Modifications. Le bouton Récupérer reste en place pendant la récupération.",
        "**Confirmation avant de fermer ou retirer** : le X du volet du Tableau demande un second clic pour terminer la session. Cliquez à nouveau sur la carte sélectionnée pour fermer uniquement le volet. Retirer un projet de la barre latérale demande aussi confirmation.",
        "**Nouvelle fenêtre depuis le menu du moniteur** : ouvrez une autre fenêtre depuis le menu pour déplacer cette fenêtre vers un autre moniteur, comme indiqué dans l'accueil.",
      ],
      de: [
        "**Flaches Design sowie helles und dunkles Thema**: Folge Windows oder wähle das Thema in den Einstellungen. Terminals, Editor und Diagramme folgen dem Thema; Terminals können auch dunkel bleiben.",
        "**Komfortableres Git-Panel**: Ziehe die Trennlinie zwischen Dateiliste und Diff in Änderungen. Die Abrufen-Schaltfläche bleibt während des Abrufens an ihrem Platz.",
        "**Bestätigung beim Beenden und Entfernen**: Das X der Board-Schublade braucht einen zweiten Klick zum Beenden der Sitzung. Klicke erneut auf die ausgewählte Karte, um nur die Schublade zu schließen. Auch das Entfernen eines Projekts aus der Seitenleiste verlangt eine Bestätigung.",
        "**Neues Fenster im Monitor-Menü**: Öffne ein weiteres Fenster im Menü zum Verschieben dieses Fensters auf einen anderen Monitor, wie im Einführungshinweis gezeigt.",
      ],
      it: [
        "**Design piatto e temi chiaro e scuro**: segui Windows o scegli il tema nelle Impostazioni. Terminali, editor e diagrammi seguono il tema; puoi anche mantenere il terminale scuro.",
        "**Pannello Git più comodo**: trascina il divisore tra l'elenco dei file e il diff in Modifiche. Il pulsante Fetch resta al suo posto durante il recupero.",
        "**Conferma prima di chiudere o rimuovere**: la X del pannello della Bacheca richiede un secondo clic per terminare la sessione. Fai di nuovo clic sulla scheda selezionata per chiudere solo il pannello. Anche rimuovere un progetto dalla barra laterale richiede conferma.",
        "**Nuova finestra dal menu del monitor**: apri un'altra finestra dal menu per spostare questa finestra su un altro monitor, come indica il suggerimento iniziale.",
      ],
      ja: [
        "**フラットなデザインとライト・ダークテーマ**：Windows に合わせるか、設定でテーマを選べます。ターミナル、エディター、図もテーマに合わせて変わり、ターミナルだけを暗く保つこともできます。",
        "**使いやすくなった Git パネル**：変更画面でファイル一覧と差分の間の仕切りをドラッグできます。取得ボタンは取得中も同じ位置に表示されます。",
        "**終了・削除前の確認**：ボードの詳細パネルの X は、もう一度クリックするとセッションを終了します。選択中のカードを再度クリックするとパネルだけを閉じます。サイドバーからプロジェクトを外す際も確認が必要です。",
        "**モニターメニューから新しいウィンドウ**：初期設定のヒントにあるように、別のモニターへウィンドウを移動するメニューから新しいウィンドウを開けます。",
      ],
      zh: [
        "**扁平设计与浅色、深色主题**：跟随 Windows，或在设置中选择主题。终端、编辑器和图表会跟随主题，也可以让终端始终保持深色。",
        "**更舒适的 Git 面板**：在更改页面拖动文件列表与差异视图之间的分隔线。获取按钮在获取期间保持原位。",
        "**结束和移除前确认**：看板详情面板的 X 需要再次点击才会结束会话。再次点击已选中的卡片只会关闭面板。将项目从侧边栏移除时也需要确认。",
        "**从显示器菜单打开新窗口**：按照首次使用提示，从将此窗口移到另一台显示器的菜单中打开新窗口。",
      ],
      ko: [
        "**평면 디자인과 밝은·어두운 테마**: Windows 설정을 따르거나 설정에서 테마를 고르세요. 터미널, 편집기, 다이어그램도 테마를 따르며 터미널만 어둡게 유지할 수도 있습니다.",
        "**더 편리한 Git 패널**: 변경 사항에서 파일 목록과 diff 사이의 구분선을 드래그하세요. 가져오기 버튼은 작업 중에도 같은 위치에 표시됩니다.",
        "**종료·제거 전 확인**: 보드 상세 패널의 X를 다시 클릭해야 세션이 종료됩니다. 선택한 카드를 다시 클릭하면 패널만 닫힙니다. 사이드바에서 프로젝트를 제거할 때도 확인이 필요합니다.",
        "**모니터 메뉴에서 새 창 열기**: 시작 안내에 표시된 대로 창을 다른 모니터로 옮기는 메뉴에서 새 창을 열 수 있습니다.",
      ],
      ru: [
        "**Плоский дизайн, светлая и тёмная темы**: следуйте настройкам Windows или выберите тему в настройках. Терминалы, редактор и диаграммы следуют теме; терминал можно оставить тёмным.",
        "**Более удобная панель Git**: перетаскивайте разделитель между списком файлов и diff в Изменениях. Кнопка Fetch остаётся на месте во время загрузки.",
        "**Подтверждение завершения и удаления**: X в панели Доски требует второго щелчка для завершения сессии. Повторный щелчок по выбранной карточке закрывает только панель. Удаление проекта из боковой панели тоже требует подтверждения.",
        "**Новое окно из меню монитора**: открывайте ещё одно окно из меню переноса окна на другой монитор, как показано в подсказке при первом запуске.",
      ],
    },
  },
  {
    version: "0.3.3",
    notes: {
      pt: [
        "**Filtro por estado** no “Para fazer” (tecla E): escolha um ou vários estados reais, como New e Committed, com as cores do Azure DevOps.",
        "**Mude o estado sem sair do Polvo** (tecla S): os estados reais do work item no Azure DevOps, ou fechar e reabrir a issue no GitHub.",
        "**Ações rápidas** (tecla .): copiar o ID para a mensagem do commit, o link ou o nome de branch, criar a branch com checkout e abrir um terminal no projeto. Itens que já têm branch local mostram um selo e abrem a sessão nela.",
        "**Resumo para a daily**: ontem, hoje e impedimentos montados a partir dos seus commits, PRs e work items, prontos para copiar. Revisões paradas há mais de um dia ficam destacadas.",
      ],
      en: [
        "**Filter by state** in “To do” (E key): pick one or more real states, such as New and Committed, in Azure DevOps colors.",
        "**Change the state without leaving Polvo** (S key): the work item's real Azure DevOps states, or close and reopen the GitHub issue.",
        "**Quick actions** (. key): copy the ID for your commit message, the link or a branch name, create the branch and check it out, and open a terminal in the project. Items that already have a local branch show a badge and open the session on it.",
        "**Standup summary**: yesterday, today and blockers built from your commits, PRs and work items, ready to copy. Reviews waiting more than a day are highlighted.",
      ],
      es: [
        "**Filtro por estado** en “Por hacer” (tecla E): elige uno o varios estados reales, como New y Committed, con los colores de Azure DevOps.",
        "**Cambia el estado sin salir de Polvo** (tecla S): los estados reales del work item en Azure DevOps, o cerrar y reabrir la issue en GitHub.",
        "**Acciones rápidas** (tecla .): copiar el ID para el mensaje del commit, el enlace o el nombre de branch, crear la branch con checkout y abrir una terminal en el proyecto. Los elementos que ya tienen branch local muestran una insignia y abren la sesión en ella.",
        "**Resumen para la daily**: ayer, hoy e impedimentos armados con tus commits, PRs y work items, listos para copiar. Las revisiones paradas más de un día se destacan.",
      ],
      fr: [
        "**Filtre par état** dans « À faire » (touche E) : choisissez un ou plusieurs états réels, comme New et Committed, aux couleurs d'Azure DevOps.",
        "**Changez l'état sans quitter Polvo** (touche S) : les vrais états du work item dans Azure DevOps, ou fermer et rouvrir l'issue GitHub.",
        "**Actions rapides** (touche .) : copier l'ID pour le message de commit, le lien ou un nom de branche, créer la branche avec checkout et ouvrir un terminal dans le projet. Les éléments qui ont déjà une branche locale affichent un badge et ouvrent la session dessus.",
        "**Résumé pour le daily** : hier, aujourd'hui et blocages, construits à partir de vos commits, PR et work items, prêts à copier. Les revues en attente depuis plus d'un jour sont mises en avant.",
      ],
      de: [
        "**Filter nach Zustand** in „Zu erledigen“ (Taste E): Wähle einen oder mehrere echte Zustände wie New und Committed, in den Azure-DevOps-Farben.",
        "**Zustand ändern, ohne Polvo zu verlassen** (Taste S): die echten Zustände des Work Items in Azure DevOps oder das GitHub-Issue schließen und wieder öffnen.",
        "**Schnellaktionen** (Taste .): ID für die Commit-Nachricht, Link oder Branch-Namen kopieren, Branch anlegen und auschecken und ein Terminal im Projekt öffnen. Einträge mit lokalem Branch zeigen ein Abzeichen und öffnen die Sitzung darauf.",
        "**Zusammenfassung fürs Daily**: gestern, heute und Hindernisse aus deinen Commits, PRs und Work Items, fertig zum Kopieren. Reviews, die länger als einen Tag warten, werden hervorgehoben.",
      ],
      it: [
        "**Filtro per stato** in “Da fare” (tasto E): scegli uno o più stati reali, come New e Committed, con i colori di Azure DevOps.",
        "**Cambia lo stato senza uscire da Polvo** (tasto S): gli stati reali del work item in Azure DevOps, oppure chiudi e riapri la issue su GitHub.",
        "**Azioni rapide** (tasto .): copia l'ID per il messaggio di commit, il link o un nome di branch, crea il branch con checkout e apri un terminale nel progetto. Gli elementi che hanno già un branch locale mostrano un badge e aprono la sessione su di esso.",
        "**Riepilogo per il daily**: ieri, oggi e impedimenti costruiti dai tuoi commit, PR e work item, pronti da copiare. Le revisioni ferme da più di un giorno sono evidenziate.",
      ],
      ja: [
        "**状態で絞り込み**（E キー）：「やること」で New や Committed など実際の状態を 1 つ以上選べます。色は Azure DevOps と同じです。",
        "**Polvo から状態を変更**（S キー）：Azure DevOps の作業項目の実際の状態、または GitHub の Issue のクローズと再オープン。",
        "**クイックアクション**（. キー）：コミットメッセージ用の ID、リンク、branch 名のコピー、branch の作成と checkout、プロジェクトでのターミナル起動。ローカル branch がある項目にはバッジが付き、その branch でセッションを開けます。",
        "**デイリー用のまとめ**：コミット、PR、作業項目から昨日・今日・障害をまとめ、そのままコピーできます。1 日以上待っているレビューは強調表示されます。",
      ],
      zh: [
        "**按状态筛选**（E 键）：在“待办”中选择一个或多个真实状态，如 New 和 Committed，颜色与 Azure DevOps 一致。",
        "**不离开 Polvo 即可更改状态**（S 键）：使用 Azure DevOps 工作项的真实状态，或关闭、重新打开 GitHub issue。",
        "**快捷操作**（. 键）：复制用于提交信息的 ID、链接或 branch 名称，创建 branch 并 checkout，在项目中打开终端。已有本地 branch 的条目会显示标记，并可直接在其上打开会话。",
        "**站会摘要**：根据你的提交、PR 和工作项生成昨天、今天和阻碍，可直接复制。等待超过一天的评审会被突出显示。",
      ],
      ko: [
        "**상태로 필터**(E 키): “할 일”에서 New, Committed 같은 실제 상태를 하나 이상 고를 수 있으며 Azure DevOps 색으로 표시됩니다.",
        "**Polvo에서 바로 상태 변경**(S 키): Azure DevOps 작업 항목의 실제 상태로 바꾸거나 GitHub 이슈를 닫고 다시 엽니다.",
        "**빠른 작업**(. 키): 커밋 메시지용 ID, 링크, branch 이름 복사, branch 생성 및 checkout, 프로젝트에서 터미널 열기. 로컬 branch가 있는 항목에는 배지가 붙고 해당 branch에서 세션을 엽니다.",
        "**데일리 요약**: 커밋, PR, 작업 항목으로 어제·오늘·장애 요소를 정리해 바로 복사할 수 있습니다. 하루 넘게 기다리는 리뷰는 강조됩니다.",
      ],
      ru: [
        "**Фильтр по состоянию** в «К выполнению» (клавиша E): выберите одно или несколько реальных состояний, например New и Committed, в цветах Azure DevOps.",
        "**Меняйте состояние, не выходя из Polvo** (клавиша S): реальные состояния рабочего элемента в Azure DevOps или закрытие и повторное открытие issue в GitHub.",
        "**Быстрые действия** (клавиша .): скопировать ID для сообщения коммита, ссылку или имя ветки, создать ветку с checkout и открыть терминал в проекте. У элементов с локальной веткой есть значок, и сессия открывается прямо в ней.",
        "**Сводка для стендапа**: вчера, сегодня и блокеры по вашим коммитам, PR и рабочим элементам — готово к копированию. Ревью, ожидающие больше дня, выделены.",
      ],
    },
  },
  {
    version: "0.3.2",
    notes: {
      pt: ["**Meu trabalho com os estados reais do Azure DevOps**: work items mostram o estado e o tipo como no Boards (Committed, Approved, Product Backlog Item…), com as cores de lá. Filtros, pendentes, grupos e sprint seguem a categoria oficial de cada estado, inclusive em processos customizados."],
      en: ["**My work with real Azure DevOps states**: work items show their state and type as in Boards (Committed, Approved, Product Backlog Item…), in Boards colors. Filters, pending items, groups and the sprint follow each state's official category, including in custom processes."],
      es: ["**Mi trabajo con los estados reales de Azure DevOps**: los work items muestran el estado y el tipo como en Boards (Committed, Approved, Product Backlog Item…), con sus colores. Filtros, pendientes, grupos y sprint siguen la categoría oficial de cada estado, también en procesos personalizados."],
      fr: ["**Mon travail avec les vrais états d'Azure DevOps** : les work items affichent leur état et leur type comme dans Boards (Committed, Approved, Product Backlog Item…), avec leurs couleurs. Filtres, éléments en attente, groupes et sprint suivent la catégorie officielle de chaque état, y compris dans les processus personnalisés."],
      de: ["**Meine Arbeit mit den echten Azure-DevOps-Zuständen**: Work Items zeigen Zustand und Typ wie in Boards (Committed, Approved, Product Backlog Item …) in den dortigen Farben. Filter, offene Einträge, Gruppen und Sprint folgen der offiziellen Kategorie jedes Zustands, auch in angepassten Prozessen."],
      it: ["**Il mio lavoro con gli stati reali di Azure DevOps**: i work item mostrano stato e tipo come in Boards (Committed, Approved, Product Backlog Item…), con i loro colori. Filtri, elementi in sospeso, gruppi e sprint seguono la categoria ufficiale di ogni stato, anche nei processi personalizzati."],
      ja: ["**マイワークで Azure DevOps の実際の状態を表示**：作業項目の状態と種類を Boards と同じ名前と色で表示します（Committed、Approved、Product Backlog Item など）。フィルター、未完了、グループ、スプリントは各状態の公式カテゴリに従い、カスタムプロセスにも対応します。"],
      zh: ["**我的工作显示 Azure DevOps 的真实状态**：工作项按 Boards 中的名称和颜色显示状态与类型（Committed、Approved、Product Backlog Item 等）。筛选、待处理、分组和冲刺都遵循每个状态的官方类别，也支持自定义流程。"],
      ko: ["**내 작업에 Azure DevOps의 실제 상태 표시**: 작업 항목의 상태와 유형을 Boards와 같은 이름과 색으로 보여 줍니다(Committed, Approved, Product Backlog Item 등). 필터, 대기 항목, 그룹, 스프린트는 각 상태의 공식 범주를 따르며 사용자 지정 프로세스도 지원합니다."],
      ru: ["**Моя работа с реальными состояниями Azure DevOps**: рабочие элементы показывают состояние и тип как в Boards (Committed, Approved, Product Backlog Item…), в тех же цветах. Фильтры, незавершённое, группы и спринт следуют официальной категории каждого состояния, в том числе в настраиваемых процессах."],
    },
  },
  {
    version: "0.3.1",
    notes: {
      pt: ["**Meu trabalho**: o Polvo não fecha mais ao abrir “Configurar” e procurar suas contas do GitHub e do Azure DevOps."],
      en: ["**My work**: Polvo no longer closes when you open “Set up” and it looks for your GitHub and Azure DevOps accounts."],
      es: ["**Mi trabajo**: Polvo ya no se cierra al abrir “Configurar” y buscar tus cuentas de GitHub y Azure DevOps."],
      fr: ["**Mon travail** : Polvo ne se ferme plus quand vous ouvrez « Configurer » et qu'il recherche vos comptes GitHub et Azure DevOps."],
      de: ["**Meine Arbeit**: Polvo schließt sich nicht mehr, wenn du „Einrichten“ öffnest und es deine GitHub- und Azure-DevOps-Konten sucht."],
      it: ["**Il mio lavoro**: Polvo non si chiude più quando apri “Configura” e cerca i tuoi account GitHub e Azure DevOps."],
      ja: ["**マイワーク**：「設定」を開いて GitHub と Azure DevOps のアカウントを検出するときに Polvo が終了してしまう問題を修正しました。"],
      zh: ["**我的工作**：打开“设置”并查找你的 GitHub 和 Azure DevOps 账户时，Polvo 不会再意外关闭。"],
      ko: ["**내 작업**: “설정”을 열어 GitHub와 Azure DevOps 계정을 찾을 때 Polvo가 종료되던 문제를 고쳤습니다."],
      ru: ["**Моя работа**: Polvo больше не закрывается, когда вы открываете «Настроить» и он ищет ваши аккаунты GitHub и Azure DevOps."],
    },
  },
  {
    version: "0.3.0",
    notes: {
      pt: [
        "**Meu trabalho** (Ctrl+Shift+3): uma nova tela com seus commits, issues e PRs do GitHub e work items, sprint e PRs do Azure DevOps, num lugar só. A lista “Para fazer” traz os bugs urgentes primeiro, filtra pendentes e só bugs, e aguenta backlogs grandes com busca, grupos e atalhos de teclado.",
        "**Leve um item para um agente** com a tecla A: implementar, implementar numa worktree nova, planejar antes ou investigar um bug, já com a descrição e os comentários no prompt. Veja e responda os comentários sem sair do Polvo, ou abra o registro no navegador com O.",
        "**Conexão simples e segura**: usa o login que você já tem no GitHub CLI e no Azure CLI (ou entre pelo navegador com um código), com PAT como alternativa. Os tokens ficam no Gerenciador de Credenciais do Windows.",
      ],
      en: [
        "**My work** (Ctrl+Shift+3): a new view with your commits, GitHub issues and PRs, and Azure DevOps work items, sprint and PRs in one place. The “To do” list puts urgent bugs first, filters pending items and bugs only, and handles large backlogs with search, groups and keyboard shortcuts.",
        "**Hand an item to an agent** with the A key: implement, implement in a new worktree, plan first or investigate a bug, with the description and comments already in the prompt. Read and reply to comments without leaving Polvo, or open the record in the browser with O.",
        "**Simple, secure connection**: reuses the login you already have in GitHub CLI and Azure CLI (or sign in through the browser with a code), with a PAT as a fallback. Tokens stay in Windows Credential Manager.",
      ],
      es: [
        "**Mi trabajo** (Ctrl+Shift+3): una nueva vista con tus commits, issues y PRs de GitHub, y work items, sprint y PRs de Azure DevOps en un solo lugar. La lista “Por hacer” pone primero los bugs urgentes, filtra pendientes y solo bugs, y aguanta backlogs grandes con búsqueda, grupos y atajos de teclado.",
        "**Lleva un elemento a un agente** con la tecla A: implementar, implementar en una worktree nueva, planificar antes o investigar un bug, con la descripción y los comentarios ya en el prompt. Lee y responde comentarios sin salir de Polvo, o abre el registro en el navegador con O.",
        "**Conexión simple y segura**: usa el inicio de sesión que ya tienes en GitHub CLI y Azure CLI (o entra por el navegador con un código), con PAT como alternativa. Los tokens se guardan en el Administrador de credenciales de Windows.",
      ],
      fr: [
        "**Mon travail** (Ctrl+Shift+3) : une nouvelle vue qui réunit vos commits, les issues et PR GitHub, et les work items, le sprint et les PR Azure DevOps. La liste « À faire » met les bugs urgents en tête, filtre les éléments en attente et les bugs, et gère les gros backlogs avec recherche, groupes et raccourcis clavier.",
        "**Confiez un élément à un agent** avec la touche A : implémenter, implémenter dans une nouvelle worktree, planifier d'abord ou enquêter sur un bug, avec la description et les commentaires déjà dans le prompt. Lisez et répondez aux commentaires sans quitter Polvo, ou ouvrez l'élément dans le navigateur avec O.",
        "**Connexion simple et sûre** : réutilise votre connexion à GitHub CLI et Azure CLI (ou connectez-vous dans le navigateur avec un code), avec un PAT en secours. Les tokens restent dans le Gestionnaire d'identification de Windows.",
      ],
      de: [
        "**Meine Arbeit** (Strg+Umschalt+3): eine neue Ansicht mit deinen Commits, GitHub-Issues und -PRs sowie Azure-DevOps-Work-Items, Sprint und PRs an einem Ort. Die Liste „Zu erledigen“ zeigt dringende Bugs zuerst, filtert offene Einträge und nur Bugs und bewältigt große Backlogs mit Suche, Gruppen und Tastenkürzeln.",
        "**Übergib einen Eintrag an einen Agenten** mit der Taste A: implementieren, in einer neuen Worktree implementieren, erst planen oder einen Bug untersuchen – Beschreibung und Kommentare stehen schon im Prompt. Lies und beantworte Kommentare direkt in Polvo oder öffne den Eintrag mit O im Browser.",
        "**Einfache, sichere Verbindung**: nutzt deine bestehende Anmeldung in GitHub CLI und Azure CLI (oder melde dich im Browser mit einem Code an), mit PAT als Alternative. Die Tokens bleiben in der Windows-Anmeldeinformationsverwaltung.",
      ],
      it: [
        "**Il mio lavoro** (Ctrl+Maiusc+3): una nuova vista con i tuoi commit, le issue e le PR di GitHub e i work item, lo sprint e le PR di Azure DevOps in un unico posto. La lista “Da fare” mette prima i bug urgenti, filtra gli elementi in sospeso e solo i bug, e regge backlog grandi con ricerca, gruppi e scorciatoie da tastiera.",
        "**Affida un elemento a un agente** con il tasto A: implementare, implementare in una nuova worktree, pianificare prima o indagare su un bug, con descrizione e commenti già nel prompt. Leggi e rispondi ai commenti senza uscire da Polvo, o apri l'elemento nel browser con O.",
        "**Connessione semplice e sicura**: usa l'accesso che hai già in GitHub CLI e Azure CLI (o accedi dal browser con un codice), con un PAT come alternativa. I token restano in Gestione credenziali di Windows.",
      ],
      ja: [
        "**マイワーク**（Ctrl+Shift+3）：コミット、GitHub の Issue と PR、Azure DevOps の作業項目・スプリント・PR を 1 か所にまとめた新しいビュー。「やること」リストは緊急のバグを先頭に表示し、未完了やバグだけの絞り込み、検索・グループ・キーボードショートカットで大きなバックログも扱えます。",
        "**A キーで項目をエージェントへ**：実装、新しい worktree での実装、先に計画、バグの調査を選べ、説明とコメントはプロンプトに入った状態で渡されます。コメントは Polvo の中で読んで返信でき、O キーでブラウザーの元の項目を開けます。",
        "**シンプルで安全な接続**：GitHub CLI と Azure CLI の既存のログインを使います（またはブラウザーでコードを入力してサインイン）。代わりに PAT も使えます。トークンは Windows 資格情報マネージャーに保存されます。",
      ],
      zh: [
        "**我的工作**（Ctrl+Shift+3）：全新视图，把你的提交、GitHub 的 issue 和 PR，以及 Azure DevOps 的工作项、冲刺和 PR 集中在一处。“待办”列表把紧急 bug 放在最前，可只看待处理项或只看 bug，并通过搜索、分组和快捷键应对大型待办列表。",
        "**按 A 键把条目交给智能体**：实现、在新 worktree 中实现、先做计划或调查 bug，描述和评论已自动放进提示词。无需离开 Polvo 即可查看和回复评论，按 O 在浏览器中打开原条目。",
        "**简单安全的连接**：复用你在 GitHub CLI 和 Azure CLI 中已有的登录（或在浏览器中输入代码登录），也可改用 PAT。令牌保存在 Windows 凭据管理器中。",
      ],
      ko: [
        "**내 작업**(Ctrl+Shift+3): 커밋, GitHub 이슈와 PR, Azure DevOps 작업 항목·스프린트·PR을 한곳에 모은 새 화면입니다. “할 일” 목록은 긴급 버그를 먼저 보여 주고, 대기 중인 항목이나 버그만 걸러 볼 수 있으며, 검색·그룹·단축키로 큰 백로그도 다룰 수 있습니다.",
        "**A 키로 항목을 에이전트에게**: 구현, 새 worktree에서 구현, 먼저 계획, 버그 조사 중에서 고를 수 있고 설명과 댓글이 프롬프트에 담겨 전달됩니다. Polvo를 떠나지 않고 댓글을 읽고 답할 수 있으며, O 키로 브라우저에서 원본 항목을 엽니다.",
        "**간단하고 안전한 연결**: GitHub CLI와 Azure CLI에 이미 로그인된 계정을 그대로 쓰거나 브라우저에서 코드로 로그인하며, PAT도 쓸 수 있습니다. 토큰은 Windows 자격 증명 관리자에 보관됩니다.",
      ],
      ru: [
        "**Моя работа** (Ctrl+Shift+3): новый экран, где собраны ваши коммиты, issues и PR из GitHub, а также рабочие элементы, спринт и PR из Azure DevOps. Список «К выполнению» показывает срочные баги первыми, фильтрует незавершённое и только баги и справляется с большими бэклогами благодаря поиску, группам и горячим клавишам.",
        "**Передайте элемент агенту** клавишей A: реализовать, реализовать в новом worktree, сначала спланировать или разобраться с багом — описание и комментарии уже будут в промпте. Читайте комментарии и отвечайте на них, не выходя из Polvo, или откройте запись в браузере клавишей O.",
        "**Простое и безопасное подключение**: используется ваш вход в GitHub CLI и Azure CLI (или вход в браузере по коду), PAT — как запасной вариант. Токены хранятся в диспетчере учётных данных Windows.",
      ],
    },
  },
  {
    version: "0.2.2",
    notes: {
      pt: ["**Telas menores**: Ajustes e os demais diálogos rolam por dentro, com os botões sempre à vista; popovers e grades se ajustam a janelas estreitas ou baixas."],
      en: ["**Smaller screens**: Settings and the other dialogs scroll inside, with their buttons always in view; popovers and grids adapt to narrow or short windows."],
      es: ["**Pantallas más pequeñas**: Ajustes y los demás diálogos se desplazan por dentro, con los botones siempre visibles; los popovers y las cuadrículas se adaptan a ventanas estrechas o bajas."],
      fr: ["**Petits écrans** : les Réglages et les autres boîtes de dialogue défilent à l’intérieur, avec les boutons toujours visibles ; popovers et grilles s’adaptent aux fenêtres étroites ou basses."],
      de: ["**Kleinere Bildschirme**: Einstellungen und die anderen Dialoge scrollen innen, die Schaltflächen bleiben immer sichtbar; Popover und Raster passen sich schmalen oder niedrigen Fenstern an."],
      it: ["**Schermi più piccoli**: Impostazioni e le altre finestre di dialogo scorrono all’interno, con i pulsanti sempre visibili; popover e griglie si adattano a finestre strette o basse."],
      ja: ["**小さな画面に対応**: 設定などのダイアログは内側でスクロールし、ボタンは常に表示されます。ポップオーバーやグリッドも狭い・低いウィンドウに合わせて調整されます。"],
      zh: ["**适配小屏幕**：设置等对话框在内部滚动，按钮始终可见；弹出框和网格会适应窄或矮的窗口。"],
      ko: ["**작은 화면 지원**: 설정과 다른 대화 상자가 내부에서 스크롤되며 버튼은 항상 보입니다. 팝오버와 그리드도 좁거나 낮은 창에 맞춰집니다."],
      ru: ["**Небольшие экраны**: настройки и другие диалоги прокручиваются внутри, кнопки всегда на виду; всплывающие окна и сетки подстраиваются под узкие и низкие окна."],
    },
  },
  {
    version: "0.2.1",
    notes: {
      pt: [
        "**Cor e ícone por projeto**: clique com o botão direito num projeto da barra lateral (ou escolha ao criar e clonar). As sessões sem cor própria herdam a cor do projeto.",
        "**Barra lateral recolhida mostra projetos**: um item por projeto, com ícone ou iniciais, quantidade de sessões e o status mais urgente; clique para ver as sessões.",
        "A caixa de commit volta para o lugar quando o repositório não tem alterações.",
        "Colaboradores na tela **Sobre** e nos READMEs, sem nomes repetidos e com link para o perfil no GitHub.",
        "Primeiras contribuições da comunidade. Obrigado, @GabrielFranciscon!",
      ],
      en: [
        "**Project color and icon**: right-click a project in the sidebar (or pick them when creating or cloning). Sessions without their own color inherit the project's.",
        "**Collapsed sidebar shows projects**: one item per project, with its icon or initials, session count and most urgent status; click to see its sessions.",
        "The commit box stays in place when the repository has no changes.",
        "Contributors in the **About** screen and the READMEs, without duplicate names and linking to their GitHub profiles.",
        "First community contributions. Thank you, @GabrielFranciscon!",
      ],
      es: [
        "**Color e icono por proyecto**: haz clic derecho en un proyecto de la barra lateral (o elígelos al crear y clonar). Las sesiones sin color propio heredan el del proyecto.",
        "**La barra lateral contraída muestra proyectos**: un elemento por proyecto, con icono o iniciales, número de sesiones y el estado más urgente; haz clic para ver sus sesiones.",
        "El cuadro de commit vuelve a su sitio cuando el repositorio no tiene cambios.",
        "Colaboradores en la pantalla **Acerca de** y en los README, sin nombres repetidos y con enlace a su perfil de GitHub.",
        "Primeras contribuciones de la comunidad. ¡Gracias, @GabrielFranciscon!",
      ],
      fr: [
        "**Couleur et icône par projet** : clic droit sur un projet dans la barre latérale (ou au moment de créer et cloner). Les sessions sans couleur propre héritent de celle du projet.",
        "**La barre latérale réduite affiche les projets** : un élément par projet, avec icône ou initiales, nombre de sessions et statut le plus urgent ; cliquez pour voir ses sessions.",
        "La zone de commit reste à sa place quand le dépôt n’a pas de modifications.",
        "Contributeurs dans l’écran **À propos** et les README, sans noms en double et avec un lien vers leur profil GitHub.",
        "Premières contributions de la communauté. Merci, @GabrielFranciscon !",
      ],
      de: [
        "**Farbe und Symbol pro Projekt**: Rechtsklick auf ein Projekt in der Seitenleiste (oder beim Erstellen und Klonen wählen). Sitzungen ohne eigene Farbe übernehmen die des Projekts.",
        "**Eingeklappte Seitenleiste zeigt Projekte**: ein Eintrag pro Projekt mit Symbol oder Initialen, Anzahl der Sitzungen und dringendstem Status; Klick zeigt die Sitzungen.",
        "Das Commit-Feld bleibt an seinem Platz, wenn das Repository keine Änderungen hat.",
        "Mitwirkende im **Info**-Fenster und in den READMEs, ohne doppelte Namen und mit Link zum GitHub-Profil.",
        "Erste Beiträge aus der Community. Danke, @GabrielFranciscon!",
      ],
      it: [
        "**Colore e icona per progetto**: clic destro su un progetto nella barra laterale (o sceglili quando crei e cloni). Le sessioni senza colore proprio ereditano quello del progetto.",
        "**La barra laterale compressa mostra i progetti**: un elemento per progetto, con icona o iniziali, numero di sessioni e stato più urgente; clicca per vedere le sessioni.",
        "La casella di commit resta al suo posto quando il repository non ha modifiche.",
        "Contributori nella schermata **Informazioni** e nei README, senza nomi duplicati e con link al profilo GitHub.",
        "Primi contributi della community. Grazie, @GabrielFranciscon!",
      ],
      ja: [
        "**プロジェクトごとの色とアイコン**: サイドバーのプロジェクトを右クリック（作成・クローン時にも選択可）。独自の色がないセッションはプロジェクトの色を引き継ぎます。",
        "**折りたたんだサイドバーにプロジェクトを表示**: プロジェクトごとに 1 項目で、アイコンまたはイニシャル、セッション数、最も急ぎの状態を表示。クリックでセッション一覧。",
        "変更がないリポジトリでもコミット欄が正しい位置に表示されます。",
        "**情報**画面と README のコントリビューター一覧から重複をなくし、GitHub プロフィールへのリンクを追加。",
        "コミュニティからの初めてのコントリビューション。ありがとう、@GabrielFranciscon！",
      ],
      zh: [
        "**按项目设置颜色和图标**：在侧边栏右键单击项目（创建和克隆时也可选择）。没有自己颜色的会话会继承项目的颜色。",
        "**折叠的侧边栏显示项目**：每个项目一项，带图标或首字母、会话数量和最紧急的状态；点击查看其会话。",
        "仓库没有更改时，提交框会保持在原位。",
        "**关于**界面和 README 中的贡献者列表不再重复，并链接到其 GitHub 个人主页。",
        "首批社区贡献。感谢 @GabrielFranciscon！",
      ],
      ko: [
        "**프로젝트별 색상과 아이콘**: 사이드바에서 프로젝트를 마우스 오른쪽 버튼으로 클릭하세요(생성·복제할 때도 선택 가능). 자체 색상이 없는 세션은 프로젝트 색상을 따릅니다.",
        "**접힌 사이드바에 프로젝트 표시**: 프로젝트마다 하나씩, 아이콘 또는 이니셜, 세션 수, 가장 급한 상태를 보여 주며 클릭하면 세션이 열립니다.",
        "저장소에 변경 사항이 없을 때도 커밋 상자가 제자리에 있습니다.",
        "**정보** 화면과 README의 기여자 목록에서 중복을 없애고 GitHub 프로필 링크를 추가했습니다.",
        "커뮤니티의 첫 기여입니다. 고마워요, @GabrielFranciscon!",
      ],
      ru: [
        "**Цвет и значок проекта**: щёлкните проект в боковой панели правой кнопкой (или выберите при создании и клонировании). Сессии без своего цвета наследуют цвет проекта.",
        "**Свёрнутая боковая панель показывает проекты**: по одному элементу на проект — значок или инициалы, число сессий и самый срочный статус; щелчок открывает сессии.",
        "Поле коммита остаётся на месте, когда в репозитории нет изменений.",
        "Участники в окне **О программе** и в README — без повторов и со ссылками на профили GitHub.",
        "Первые вклады сообщества. Спасибо, @GabrielFranciscon!",
      ],
    },
  },
  {
    version: "0.2.0",
    notes: {
      pt: [
        "**Gerenciador de Git** integrado: alterações, diff com seleção de linhas, commit, branches, histórico, stash, pull requests e conflitos. Abra com `Ctrl+Shift+G` ou pelo ícone de branch na barra de título, em cada sessão e na barra lateral.",
        "**Os agentes ajudam no Git**: mensagem de commit gerada pelo Claude, revisão das alterações, resolução de conflitos e explicação de commits.",
        "**Nova branch numa worktree** com uma sessão do agente já aberta nela, para vários agentes trabalharem no mesmo repositório sem conflito.",
        "**Stash fácil**: guarde tudo ou um arquivo só, veja o conteúdo e restaure com um clique.",
        "**Selos de Git** na barra lateral e na barra de título: arquivos alterados, commits para enviar e para puxar.",
        "**Polvo animado** na marca e interface mais alinhada.",
      ],
      en: [
        "**Built-in Git manager**: changes, diff with line selection, commit, branches, history, stash, pull requests and conflicts. Open it with `Ctrl+Shift+G` or the branch icon in the title bar, on each session and in the sidebar.",
        "**Agents help with Git**: commit messages written by Claude, change reviews, conflict resolution and commit explanations.",
        "**New branch in a worktree** with an agent session already open in it, so several agents can work on the same repository without clashing.",
        "**Easy stash**: stash everything or a single file, preview it and restore with one click.",
        "**Git badges** in the sidebar and title bar: changed files, commits to push and to pull.",
        "**Animated Polvo** in the logo and a more aligned interface.",
      ],
      es: [
        "**Gestor de Git** integrado: cambios, diff con selección de líneas, commit, ramas, historial, stash, pull requests y conflictos. Ábrelo con `Ctrl+Shift+G` o con el icono de rama en la barra de título, en cada sesión y en la barra lateral.",
        "**Los agentes ayudan con Git**: mensajes de commit escritos por Claude, revisión de cambios, resolución de conflictos y explicación de commits.",
        "**Nueva rama en un worktree** con una sesión del agente ya abierta, para que varios agentes trabajen en el mismo repositorio sin chocar.",
        "**Stash fácil**: guarda todo o un solo archivo, mira el contenido y restáuralo con un clic.",
        "**Indicadores de Git** en la barra lateral y la barra de título: archivos cambiados, commits por enviar y por traer.",
        "**Polvo animado** en el logo e interfaz mejor alineada.",
      ],
      fr: [
        "**Gestionnaire Git** intégré : modifications, diff avec sélection de lignes, commit, branches, historique, stash, pull requests et conflits. Ouvrez-le avec `Ctrl+Shift+G` ou l’icône de branche dans la barre de titre, sur chaque session et dans la barre latérale.",
        "**Les agents aident avec Git** : messages de commit rédigés par Claude, revue des modifications, résolution des conflits et explication des commits.",
        "**Nouvelle branche dans un worktree** avec une session d’agent déjà ouverte, pour que plusieurs agents travaillent sur le même dépôt sans se gêner.",
        "**Stash facile** : mettez tout ou un seul fichier de côté, consultez le contenu et restaurez en un clic.",
        "**Badges Git** dans la barre latérale et la barre de titre : fichiers modifiés, commits à pousser et à tirer.",
        "**Polvo animé** dans le logo et interface mieux alignée.",
      ],
      de: [
        "**Integrierte Git-Verwaltung**: Änderungen, Diff mit Zeilenauswahl, Commit, Branches, Verlauf, Stash, Pull Requests und Konflikte. Öffnen mit `Strg+Umschalt+G` oder über das Branch-Symbol in der Titelleiste, an jeder Sitzung und in der Seitenleiste.",
        "**Agenten helfen bei Git**: Commit-Nachrichten von Claude, Review der Änderungen, Konfliktlösung und Erklärung von Commits.",
        "**Neuer Branch in einem Worktree** mit bereits geöffneter Agenten-Sitzung, damit mehrere Agenten ohne Konflikte im selben Repository arbeiten.",
        "**Einfacher Stash**: alles oder nur eine Datei stashen, Inhalt ansehen und mit einem Klick wiederherstellen.",
        "**Git-Badges** in Seitenleiste und Titelleiste: geänderte Dateien, Commits zum Pushen und Pullen.",
        "**Animierter Polvo** im Logo und sauber ausgerichtete Oberfläche.",
      ],
      it: [
        "**Gestore Git** integrato: modifiche, diff con selezione delle righe, commit, branch, cronologia, stash, pull request e conflitti. Aprilo con `Ctrl+Shift+G` o con l’icona del branch nella barra del titolo, in ogni sessione e nella barra laterale.",
        "**Gli agenti aiutano con Git**: messaggi di commit scritti da Claude, revisione delle modifiche, risoluzione dei conflitti e spiegazione dei commit.",
        "**Nuovo branch in un worktree** con una sessione dell’agente già aperta, così più agenti lavorano sullo stesso repository senza conflitti.",
        "**Stash semplice**: salva tutto o un solo file, guardane il contenuto e ripristinalo con un clic.",
        "**Indicatori Git** nella barra laterale e nella barra del titolo: file modificati, commit da inviare e da scaricare.",
        "**Polvo animato** nel logo e interfaccia più allineata.",
      ],
      ja: [
        "**Git マネージャーを内蔵**: 変更、行単位で選べる差分、コミット、ブランチ、履歴、スタッシュ、プルリクエスト、コンフリクト。`Ctrl+Shift+G`、またはタイトルバー・各セッション・サイドバーのブランチアイコンから開けます。",
        "**エージェントが Git を手伝います**: Claude によるコミットメッセージ作成、変更のレビュー、コンフリクト解決、コミットの説明。",
        "**ワークツリーに新しいブランチ**を作り、エージェントのセッションをそのまま開始。複数のエージェントが同じリポジトリで衝突せずに作業できます。",
        "**かんたんスタッシュ**: すべて、またはファイル 1 つだけを退避し、内容を確認してワンクリックで復元。",
        "**Git バッジ**をサイドバーとタイトルバーに表示: 変更ファイル、プッシュ・プル待ちのコミット。",
        "ロゴの**ポルボがアニメーション**し、画面の配置も整いました。",
      ],
      zh: [
        "**内置 Git 管理器**：更改、可按行选择的差异、提交、分支、历史、储藏、拉取请求和冲突。用 `Ctrl+Shift+G` 打开，或点击标题栏、每个会话和侧边栏中的分支图标。",
        "**智能体协助 Git**：由 Claude 撰写提交说明、审查更改、解决冲突并解释提交。",
        "**在工作树中新建分支**，并直接打开智能体会话，让多个智能体在同一仓库中互不干扰地工作。",
        "**轻松储藏**：储藏全部或单个文件，预览内容，一键恢复。",
        "**Git 徽标**显示在侧边栏和标题栏：已更改的文件、待推送和待拉取的提交。",
        "标志中的 **Polvo 会动了**，界面也更加整齐。",
      ],
      ko: [
        "**내장 Git 관리자**: 변경 사항, 줄 단위 선택이 되는 diff, 커밋, 브랜치, 기록, 스태시, 풀 리퀘스트, 충돌. `Ctrl+Shift+G` 또는 제목 표시줄·각 세션·사이드바의 브랜치 아이콘으로 엽니다.",
        "**에이전트가 Git을 도와줍니다**: Claude가 쓰는 커밋 메시지, 변경 사항 리뷰, 충돌 해결, 커밋 설명.",
        "**워크트리에 새 브랜치**를 만들고 에이전트 세션을 바로 열어, 여러 에이전트가 같은 저장소에서 충돌 없이 작업합니다.",
        "**쉬운 스태시**: 전체 또는 파일 하나만 보관하고, 내용을 미리 보고, 클릭 한 번으로 복원합니다.",
        "사이드바와 제목 표시줄의 **Git 배지**: 변경된 파일, 푸시·풀할 커밋.",
        "로고의 **Polvo 애니메이션**과 더 깔끔하게 정렬된 인터페이스.",
      ],
      ru: [
        "**Встроенный менеджер Git**: изменения, diff с выбором строк, коммиты, ветки, история, stash, pull request и конфликты. Открывается через `Ctrl+Shift+G` или значок ветки в заголовке окна, у каждой сессии и в боковой панели.",
        "**Агенты помогают с Git**: сообщения коммитов от Claude, ревью изменений, разрешение конфликтов и объяснение коммитов.",
        "**Новая ветка в worktree** сразу с открытой сессией агента — несколько агентов работают в одном репозитории без конфликтов.",
        "**Простой stash**: спрячьте всё или один файл, посмотрите содержимое и восстановите в один клик.",
        "**Значки Git** в боковой панели и заголовке: изменённые файлы, коммиты для отправки и получения.",
        "**Анимированный Polvo** в логотипе и более ровный интерфейс.",
      ],
    },
  },
];

/** Compara versões "a.b.c". */
export function cmpVersion(a: string, b: string): number {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) if ((pa[i] ?? 0) !== (pb[i] ?? 0)) return (pa[i] ?? 0) - (pb[i] ?? 0);
  return 0;
}
